# Generated by Django 5.2.5 on 2025-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
